
name: GitHub-Context

on:
  pull_request:
        types: [opened, reopened, labeled, synchronize]
  workflow_dispatch:

jobs:
  J1:
    runs-on: ubuntu-latest
    steps:      
      - name: Prints J1 Env
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
