
name: GitHub-Context

on:
  pull_request:
        types: [opened, reopened, labeled, synchronize]
  workflow_dispatch:
  
env:
    readyForDevelopBranch: ${{false && github.base_ref == 'develop' && github.event.pull_request.draft == false && github.event.pull_request.state == 'open'}}

jobs:
#   J1:
#     runs-on: ubuntu-latest
#     steps:      
#       - name: Prints J1 Env
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: |
#           echo "$GITHUB_CONTEXT"
  J2:
    runs-on: ubuntu-latest
    steps:      
      - name: Prints J2 1
        run: echo "$readyForDevelopBranch"
          
      - name: Prints J2 2
        if: ${{ env.readyForDevelopBranch == 'true' }} && true
        run: echo "I am 2"
          
      - name: Prints J2 3
        if: ${{ env.readyForDevelopBranch == 'false' }}
        run: echo "I am 3"
        
      - name: Prints J2 4
        if: ${{ env.readyForDevelopBranch == false }}
        run: echo "I am 4"
        
      - name: Prints J2 5
        if: 'true'
        run: echo "I am 5"
        
      - name: Prints J2 6
        if: 'false'
        run: echo "I am 6"
        
      - name: Prints J2 7
        if: ${{ env.readyForDevelopBranch && true }} == 'false'
        run: echo "I am 7"
        
      - name: Prints J2 8
        if: ${{ env.readyForDevelopBranch && true }} == 'true'
        run: echo "I am 8"
