
name: Multiple-Jobs-T1

on:
  workflow_dispatch:

env:
  abc: 123

jobs:
  J1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        
      - name: Prints J1 log
        run: node --version
      
      - name: Prints J1 Env
        env: 
          aa: 22
        run: |
          echo $aa
          echo $abc
          
  J2:
    runs-on: ubuntu-latest
    needs: [J1]
    steps:
        - name: Prints J2 log
          run: node --version
  J3:
    runs-on: ubuntu-latest
    steps:
      - name: Prints J3 text
        run: npm --version
