
name: Multiple-Jobs-T1

on:
  workflow_dispatch:

env:
  abc: 123

jobs:
  J1:
    runs-on: nodejs
    steps:
      - name: Prints J1 text
        run: echo 'Job 01'
        
      - name: Prints J1 log
        run: node --version
      
      - name: Prints J1 Env1
        env: 
          aa: 22
        run: echo $aa
        
      - name: Prints J1 Env2
        run: |
          env
          echo $abc
        
      - name: Prints J1 Env3
        run: echo $abc
  J2:
    runs-on: ubuntu-latest
    needs: [J1]
    steps:
      - name: Prints J2 text
        run: echo 'Job 02'
      - name: J2 Fails here
        run: 2/0
  J3:
    runs-on: ubuntu-latest
    needs: [J1, J2]
    steps:
      - name: Prints J3 text
        run: echo 'Job 03'
